# Generated by Django 5.0.3 on 2024-04-09 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_image_car_preview'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='images',
            field=models.ManyToManyField(to='product.image'),
        ),
    ]
